#pragma once
#include <cstddef>
#include <cstdint>
#include <type_traits>

enum PICO_HUB_ADC : uint8_t
{
	PICO_HUB_ADC_GPIO_26            = 0x1, // ADC0/GP26
	PICO_HUB_ADC_GPIO_27            = 0x2, // ADC1/GP27
	PICO_HUB_ADC_GPIO_28            = 0x4, // ADC2/GP28
	PICO_HUB_ADC_SYSTEM_VOLTAGE     = 0x8, // ADC3/GP29/VSYS
	PICO_HUB_ADC_SYSTEM_TEMPERATURE = 0x10 // ADC4/TSYS
};

enum PICO_HUB_I2C : uint8_t
{
	PICO_HUB_I2C_BUS_0, // i2c0
	PICO_HUB_I2C_BUS_1, // i2c1
	PICO_HUB_I2C_BUS_COUNT
};

enum PICO_HUB_PWM : uint8_t
{
	PICO_HUB_PWM_,
};

enum PICO_HUB_SPI : uint8_t
{
	PICO_HUB_SPI_BUS_0, // spi0
	PICO_HUB_SPI_BUS_1, // spi1
	PICO_HUB_SPI_BUS_COUNT
};

enum PICO_HUB_GPIO : uint8_t
{
	PICO_HUB_GPIO_0,
	PICO_HUB_GPIO_1,
	PICO_HUB_GPIO_2,
	PICO_HUB_GPIO_3,
	PICO_HUB_GPIO_4,
	PICO_HUB_GPIO_5,
	PICO_HUB_GPIO_6,
	PICO_HUB_GPIO_7,
	PICO_HUB_GPIO_8,
	PICO_HUB_GPIO_9,
	PICO_HUB_GPIO_10,
	PICO_HUB_GPIO_11,
	PICO_HUB_GPIO_12,
	PICO_HUB_GPIO_13,
	PICO_HUB_GPIO_14,
	PICO_HUB_GPIO_15,
	PICO_HUB_GPIO_16,
	PICO_HUB_GPIO_17,
	PICO_HUB_GPIO_18,
	PICO_HUB_GPIO_19,
	PICO_HUB_GPIO_20,
	PICO_HUB_GPIO_21,
	PICO_HUB_GPIO_22,
	PICO_HUB_GPIO_23,
	PICO_HUB_GPIO_24,
	PICO_HUB_GPIO_25,
	PICO_HUB_GPIO_26,
	PICO_HUB_GPIO_27,
	PICO_HUB_GPIO_28,
	PICO_HUB_GPIO_29,
	PICO_HUB_GPIO_COUNT,
	PICO_HUB_GPIO_LED = PICO_HUB_GPIO_25,

	PICO_HUB_GPIO_PULL_UP   = 0x1,
	PICO_HUB_GPIO_PULL_DOWN = 0x2,

	PICO_HUB_GPIO_SLEW_SLOW = 0,
	PICO_HUB_GPIO_SLEW_FAST = 1,

	PICO_HUB_GPIO_VALUE_LOW  = 0,
	PICO_HUB_GPIO_VALUE_HIGH = 1,

	PICO_HUB_GPIO_DIRECTION_IN  = 0,
	PICO_HUB_GPIO_DIRECTION_OUT = 1,

	PICO_HUB_GPIO_DRIVE_STRENGTH_2MA  = 0,
	PICO_HUB_GPIO_DRIVE_STRENGTH_4MA  = 1,
	PICO_HUB_GPIO_DRIVE_STRENGTH_8MA  = 2,
	PICO_HUB_GPIO_DRIVE_STRENGTH_12MA = 3,
};

enum PICO_HUB_UART : uint8_t
{
	PICO_HUB_UART_BUS_0, // uart0
	PICO_HUB_UART_BUS_1, // uart1
	PICO_HUB_UART_BUS_COUNT
};

enum PICO_HUB_VOLTAGE : uint8_t
{
	PICO_HUB_VOLTAGE_0_85 = 0b00110,
	PICO_HUB_VOLTAGE_0_90 = 0b00111,
	PICO_HUB_VOLTAGE_0_95 = 0b01000,
	PICO_HUB_VOLTAGE_1_00 = 0b01001,
	PICO_HUB_VOLTAGE_1_05 = 0b01010,
	PICO_HUB_VOLTAGE_1_10 = 0b01011,
	PICO_HUB_VOLTAGE_1_15 = 0b01100,
	PICO_HUB_VOLTAGE_1_20 = 0b01101,
	PICO_HUB_VOLTAGE_1_25 = 0b01110,
	PICO_HUB_VOLTAGE_1_30 = 0b01111,

	PICO_HUB_VOLTAGE_MIN     = PICO_HUB_VOLTAGE_0_85,
	PICO_HUB_VOLTAGE_MAX     = PICO_HUB_VOLTAGE_1_30,
	PICO_HUB_VOLTAGE_DEFAULT = PICO_HUB_VOLTAGE_1_10
};

enum PICO_HUB_OPCODES : uint8_t
{
	PICO_HUB_OPCODE_GET_ID,
	PICO_HUB_OPCODE_GET_LED,
	PICO_HUB_OPCODE_SET_LED,
	PICO_HUB_OPCODE_GET_CLOCK,
	PICO_HUB_OPCODE_SET_CLOCK,
	PICO_HUB_OPCODE_GET_LATENCY,
	PICO_HUB_OPCODE_GET_VOLTAGE,
	PICO_HUB_OPCODE_SET_VOLTAGE,
	PICO_HUB_OPCODE_RESTART,
	PICO_HUB_OPCODE_SHUTDOWN,

	PICO_HUB_OPCODE_ADC_INIT,
	PICO_HUB_OPCODE_ADC_DEINIT,
	PICO_HUB_OPCODE_ADC_GET_CHANNEL,
	PICO_HUB_OPCODE_ADC_SET_CHANNEL,
	PICO_HUB_OPCODE_ADC_READ,

	PICO_HUB_OPCODE_I2C_INIT,
	PICO_HUB_OPCODE_I2C_DEINIT,
	PICO_HUB_OPCODE_I2C_READ,
	PICO_HUB_OPCODE_I2C_WRITE,
	PICO_HUB_OPCODE_I2C_WRITE_READ,

	PICO_HUB_OPCODE_PWM_INIT,
	PICO_HUB_OPCODE_PWM_DEINIT,
	PICO_HUB_OPCODE_PWM_,

	PICO_HUB_OPCODE_SPI_INIT,
	PICO_HUB_OPCODE_SPI_DEINIT,
	PICO_HUB_OPCODE_SPI_READ,
	PICO_HUB_OPCODE_SPI_WRITE,
	PICO_HUB_OPCODE_SPI_WRITE_READ,

	PICO_HUB_OPCODE_GPIO_INIT,
	PICO_HUB_OPCODE_GPIO_DEINIT,
	PICO_HUB_OPCODE_GPIO_GET_PULL_UP,
	PICO_HUB_OPCODE_GPIO_SET_PULL_UP,
	PICO_HUB_OPCODE_GPIO_GET_PULL_DOWN,
	PICO_HUB_OPCODE_GPIO_SET_PULL_DOWN,
	PICO_HUB_OPCODE_GPIO_GET_DIRECTION,
	PICO_HUB_OPCODE_GPIO_SET_DIRECTION,
	PICO_HUB_OPCODE_GPIO_GET_DRIVE_STRENGTH,
	PICO_HUB_OPCODE_GPIO_SET_DRIVE_STRENGTH,
	PICO_HUB_OPCODE_GPIO_READ,
	PICO_HUB_OPCODE_GPIO_WRITE,

	PICO_HUB_OPCODE_UART_INIT,
	PICO_HUB_OPCODE_UART_DEINIT,
	PICO_HUB_OPCODE_UART_READ,
	PICO_HUB_OPCODE_UART_WRITE,

	PICO_HUB_OPCODES_COUNT
};

enum PICO_HUB_PACKET_TYPES : uint8_t
{
	PICO_HUB_PACKET_TYPE_REQUEST,
	PICO_HUB_PACKET_TYPE_RESPONSE
};

#define PICO_HUB_PACKET(opcode, type, ...) \
	template<> struct pico_hub_packet<opcode, type> __VA_ARGS__; \
	static_assert(std::is_trivial<pico_hub_packet<opcode, type>>::value && std::is_standard_layout<pico_hub_packet<opcode, type>>::value)

#pragma pack(push, 1)
template<PICO_HUB_OPCODES OPCODE, PICO_HUB_PACKET_TYPES TYPE>
struct pico_hub_packet;

struct pico_hub_packet_header
{
	PICO_HUB_OPCODES opcode;
	uint8_t          length;
};

template<PICO_HUB_OPCODES OPCODE, PICO_HUB_PACKET_TYPES TYPE, typename = void>
struct pico_hub_packet_is_defined
{
	static constexpr bool value = false;
};
template<PICO_HUB_OPCODES OPCODE, PICO_HUB_PACKET_TYPES TYPE>
struct pico_hub_packet_is_defined<OPCODE, TYPE, std::void_t<decltype(sizeof(pico_hub_packet<OPCODE, TYPE>))>>
{
	static constexpr bool value = true;
};

template<PICO_HUB_OPCODES OPCODE>
using pico_hub_packet_request = pico_hub_packet<OPCODE, PICO_HUB_PACKET_TYPE_REQUEST>;
template<PICO_HUB_OPCODES OPCODE>
using pico_hub_packet_response = pico_hub_packet<OPCODE, PICO_HUB_PACKET_TYPE_RESPONSE>;

template<PICO_HUB_OPCODES OPCODE, bool IS_REQUEST_DEFINED, bool IS_RESPONSE_DEFINED>
struct _pico_hub_packet
{
};
template<PICO_HUB_OPCODES OPCODE>
struct _pico_hub_packet<OPCODE, true, true>
{
	pico_hub_packet_request<OPCODE>  request;
	pico_hub_packet_response<OPCODE> response;
};
template<PICO_HUB_OPCODES OPCODE>
struct _pico_hub_packet<OPCODE, true, false>
{
	pico_hub_packet_request<OPCODE> request;
};
template<PICO_HUB_OPCODES OPCODE>
struct _pico_hub_packet<OPCODE, false, true>
{
	pico_hub_packet_response<OPCODE> response;
};

template<PICO_HUB_OPCODES OPCODE>
using _pico_hub_packets = _pico_hub_packet<OPCODE, pico_hub_packet_is_defined<OPCODE, PICO_HUB_PACKET_TYPE_REQUEST>::value, pico_hub_packet_is_defined<OPCODE, PICO_HUB_PACKET_TYPE_RESPONSE>::value>;

PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_ID,                  PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_ID,                  PICO_HUB_PACKET_TYPE_RESPONSE, { uint64_t value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_LED,                 PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_LED,                 PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_LED,                 PICO_HUB_PACKET_TYPE_REQUEST,  { bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_LED,                 PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_CLOCK,               PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_CLOCK,               PICO_HUB_PACKET_TYPE_RESPONSE, { uint32_t value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_CLOCK,               PICO_HUB_PACKET_TYPE_REQUEST,  { uint32_t value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_CLOCK,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_LATENCY,             PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_LATENCY,             PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_VOLTAGE,             PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GET_VOLTAGE,             PICO_HUB_PACKET_TYPE_RESPONSE, { PICO_HUB_VOLTAGE value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_VOLTAGE,             PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_VOLTAGE value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SET_VOLTAGE,             PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_RESTART,                 PICO_HUB_PACKET_TYPE_REQUEST,  { bool restart_to_mass_storage; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_RESTART,                 PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SHUTDOWN,                PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SHUTDOWN,                PICO_HUB_PACKET_TYPE_RESPONSE, { });

PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_INIT,                PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_ADC channels; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_INIT,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_DEINIT,              PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_DEINIT,              PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_GET_CHANNEL,         PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_GET_CHANNEL,         PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; PICO_HUB_ADC value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_SET_CHANNEL,         PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_ADC value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_SET_CHANNEL,         PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_READ,                PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_ADC_READ,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; uint16_t value; PICO_HUB_ADC channel; });

PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_INIT,                PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_I2C bus; uint8_t scl; uint8_t sda; uint32_t baud; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_INIT,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_DEINIT,              PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_I2C bus; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_DEINIT,              PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_READ,                PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_I2C bus; uint8_t address; uint32_t size; bool stop; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_READ,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_WRITE,               PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_I2C bus; uint8_t address; uint32_t size; bool stop; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_WRITE,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_WRITE_READ,          PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_I2C bus; uint8_t address; uint32_t size[2]; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_I2C_WRITE_READ,          PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });

PICO_HUB_PACKET(PICO_HUB_OPCODE_PWM_INIT,                PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_PWM_INIT,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_PWM_DEINIT,              PICO_HUB_PACKET_TYPE_REQUEST,  { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_PWM_DEINIT,              PICO_HUB_PACKET_TYPE_RESPONSE, { });

PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_INIT,                PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_SPI bus; uint8_t miso; uint8_t mosi; uint8_t clock; uint8_t cs; uint32_t baud; bool slave; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_INIT,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_DEINIT,              PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_SPI bus; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_DEINIT,              PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_READ,                PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_SPI bus; uint32_t size; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_READ,                PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_WRITE,               PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_SPI bus; uint32_t size; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_WRITE,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_WRITE_READ,          PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_SPI bus; uint32_t size; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_SPI_WRITE_READ,          PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });

PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_INIT,               PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; bool direction; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_INIT,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_DEINIT,             PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_DEINIT,             PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_PULL_UP,        PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_PULL_UP,        PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_PULL_UP,        PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_PULL_UP,        PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_PULL_DOWN,      PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_PULL_DOWN,      PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_PULL_DOWN,      PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_PULL_DOWN,      PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_DIRECTION,      PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_DIRECTION,      PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_DIRECTION,      PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_DIRECTION,      PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_DRIVE_STRENGTH, PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_GET_DRIVE_STRENGTH, PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; uint8_t value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_DRIVE_STRENGTH, PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; uint8_t value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_SET_DRIVE_STRENGTH, PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_READ,               PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_READ,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_WRITE,              PICO_HUB_PACKET_TYPE_REQUEST,  { uint8_t pin; bool value; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_GPIO_WRITE,              PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });

PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_INIT,               PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_UART bus; uint8_t rx; uint8_t tx; uint32_t baud; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_INIT,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_DEINIT,             PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_UART bus; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_DEINIT,             PICO_HUB_PACKET_TYPE_RESPONSE, { });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_READ,               PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_UART bus; uint32_t size; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_READ,               PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_WRITE,              PICO_HUB_PACKET_TYPE_REQUEST,  { PICO_HUB_UART bus; uint32_t size; });
PICO_HUB_PACKET(PICO_HUB_OPCODE_UART_WRITE,              PICO_HUB_PACKET_TYPE_RESPONSE, { bool success; });

union pico_hub_packets
{
	_pico_hub_packets<PICO_HUB_OPCODE_GET_ID>                  get_id;

	_pico_hub_packets<PICO_HUB_OPCODE_GET_LED>                 get_led;
	_pico_hub_packets<PICO_HUB_OPCODE_SET_LED>                 set_led;

	_pico_hub_packets<PICO_HUB_OPCODE_GET_CLOCK>               get_clock;
	_pico_hub_packets<PICO_HUB_OPCODE_SET_CLOCK>               set_clock;

	_pico_hub_packets<PICO_HUB_OPCODE_GET_LATENCY>             get_latency;

	_pico_hub_packets<PICO_HUB_OPCODE_GET_VOLTAGE>             get_voltage;
	_pico_hub_packets<PICO_HUB_OPCODE_SET_VOLTAGE>             set_voltage;

	_pico_hub_packets<PICO_HUB_OPCODE_RESTART>                 restart;
	_pico_hub_packets<PICO_HUB_OPCODE_SHUTDOWN>                shutdown;

	_pico_hub_packets<PICO_HUB_OPCODE_ADC_INIT>                adc_init;
	_pico_hub_packets<PICO_HUB_OPCODE_ADC_DEINIT>              adc_deinit;
	_pico_hub_packets<PICO_HUB_OPCODE_ADC_GET_CHANNEL>         adc_get_channel;
	_pico_hub_packets<PICO_HUB_OPCODE_ADC_SET_CHANNEL>         adc_set_channel;
	_pico_hub_packets<PICO_HUB_OPCODE_ADC_READ>                adc_read;

	_pico_hub_packets<PICO_HUB_OPCODE_I2C_INIT>                i2c_init;
	_pico_hub_packets<PICO_HUB_OPCODE_I2C_DEINIT>              i2c_deinit;
	_pico_hub_packets<PICO_HUB_OPCODE_I2C_READ>                i2c_read;
	_pico_hub_packets<PICO_HUB_OPCODE_I2C_WRITE>               i2c_write;
	_pico_hub_packets<PICO_HUB_OPCODE_I2C_WRITE_READ>          i2c_write_read;

	_pico_hub_packets<PICO_HUB_OPCODE_PWM_INIT>                pwm_init;
	_pico_hub_packets<PICO_HUB_OPCODE_PWM_DEINIT>              pwm_deinit;

	_pico_hub_packets<PICO_HUB_OPCODE_SPI_INIT>                spi_init;
	_pico_hub_packets<PICO_HUB_OPCODE_SPI_DEINIT>              spi_deinit;
	_pico_hub_packets<PICO_HUB_OPCODE_SPI_READ>                spi_read;
	_pico_hub_packets<PICO_HUB_OPCODE_SPI_WRITE>               spi_write;
	_pico_hub_packets<PICO_HUB_OPCODE_SPI_WRITE_READ>          spi_write_read;

	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_INIT>               gpio_init;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_DEINIT>             gpio_deinit;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_GET_PULL_UP>        gpio_get_pull_up;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_SET_PULL_UP>        gpio_set_pull_up;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_GET_PULL_DOWN>      gpio_get_pull_down;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_SET_PULL_DOWN>      gpio_set_pull_down;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_GET_DIRECTION>      gpio_get_direction;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_SET_DIRECTION>      gpio_set_direction;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_GET_DRIVE_STRENGTH> gpio_get_drive_strength;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_SET_DRIVE_STRENGTH> gpio_set_drive_strength;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_READ>               gpio_read;
	_pico_hub_packets<PICO_HUB_OPCODE_GPIO_WRITE>              gpio_write;

	_pico_hub_packets<PICO_HUB_OPCODE_UART_INIT>               uart_init;
	_pico_hub_packets<PICO_HUB_OPCODE_UART_DEINIT>             uart_deinit;
	_pico_hub_packets<PICO_HUB_OPCODE_UART_READ>               uart_read;
	_pico_hub_packets<PICO_HUB_OPCODE_UART_WRITE>              uart_write;
};
#pragma pack(pop)
